language: node_js
services:
  - docker
before_install:
  - docker build -t puneetghodasara/website-nodejs .
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push puneetghodasara/website-nodejs