# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureContainerRegistry: $(azureSubscriptionEndpoint).azurecr.io

steps:
- task: DecryptFile@1
  displayName: Decrypting Key
  inputs:
    cipher: 'aes-256-ecb'
    inFile: keys/key.pem.azure.enc
    passphrase: $(encryptionKey)
    outFile: keys/key.pem
- task: DecryptFile@1
  displayName: Decrypting Certificate
  inputs:
    cipher: 'aes-256-ecb'
    inFile: keys/cert.pem.azure.enc
    passphrase: $(encryptionKey)
    outFile: keys/cert.pem
- task: DecryptFile@1
  displayName: Decrypting config.ini
  inputs:
    cipher: 'aes-256-ecb'
    inFile: keys/config.ini.azure.enc
    passphrase: $(encryptionKey)
    outFile: keys/config.ini
- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: Dockerfile
    imageName: $(imageName)
- task: Docker@1
  displayName: Push image
  inputs:
    command: push
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(imageName)
