version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting to build
  build:
    commands:
      - echo Building Docker image started on `date`
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images