steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=keys/cert.pem.gcp.enc
  - --plaintext-file=keys/cert.pem
  - --location=global
  - --keyring=puneetghodasara
  - --key=website-key

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=keys/key.pem.gcp.enc
  - --plaintext-file=keys/key.pem
  - --location=global
  - --keyring=puneetghodasara
  - --key=website-key

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=keys/config.ini.gcp.enc
  - --plaintext-file=keys/config.ini
  - --location=global
  - --keyring=puneetghodasara
  - --key=website-key

- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://source.developers.google.com/p/virtual-bytes/r/story']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/website-nodejs', '.']

- name: gcr.io/cloud-builders/gcloud
  args:
  - compute
  - instances
  - reset
  - website-nodejs
  - --zone=us-central1-b

images: ['gcr.io/$PROJECT_ID/website-nodejs:latest']