version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
  gcp-cli: circleci/gcp-cli@1.3.0
  aws-ecr: circleci/aws-ecr@3.1.0
  aws-cli: circleci/aws-cli@0.1.13
  gcp-gcr: circleci/gcp-gcr@0.0.4
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Decrypting Secrets
          command: |
            openssl aes-256-ecb -d -in keys/key.pem.enc -out keys/key.pem -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/cert.pem.enc -out keys/cert.pem -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/config.ini.enc -out keys/config.ini -pass pass:$ENCRYPTION_PASSPHRASE
#            openssl aes-256-ecb -d -in keys/virtualbytes.json.enc -out keys/virtualbytes.json -pass pass:$ENCRYPTION_PASSPHRASE
      - run:
          name: Downloading stories
          command: |
            mkdir story
            gsutil -m cp -r gs://story.puneetghodasara.com/* story/
      - run:
          name: Cleaning up before build
          command: |
            rm keys/*.enc
#            rm keys/virtualbytes.json
      - run:
          name: Add revision
          command: |
            echo $CIRCLE_BUILD_NUM > revision.info
      - docker-publish/check
      - docker-publish/build:
          tag: $CUSTOM_TAG
      - docker-publish/deploy:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG
  aws-push:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - run:
          name: Python Preparation
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
      - aws-cli/install
      - aws-cli/configure
      - docker-publish/check
      - run:
          name: Tagging for AWS cloud
          command: |
            docker pull $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG
            docker tag $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG $AWS_ACCOUNT_NUMBER.dkr-ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG
            docker images
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $CIRCLE_PROJECT_REPONAME
          tag: $CUSTOM_TAG
  gcp-push:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize
      - docker-publish/check
      - gcp-gcr/gcr-auth
      - run:
          name: Tagging for Google cloud
          command: |
            docker pull $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG
            docker tag $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG gcr.io/$GOOGLE_PROJECT_ID/$CIRCLE_PROJECT_REPONAME:$CUSTOM_TAG
            docker images
      - gcp-gcr/push-image:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CUSTOM_TAG
workflows:
  build-flow:
    jobs:
      - build
      - aws-push:
          requires:
            - build
      - gcp-push:
          requires:
            - build

