version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
  gcp-cli: circleci/gcp-cli@1.3.0
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Preparing GSUtil.
          command: |
            openssl aes-256-ecb -d -in keys/key.pem.enc -out keys/key.pem -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/cert.pem.enc -out keys/cert.pem -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/config.ini.enc -out keys/config.ini -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/virtualbytes.json.enc -out keys/virtualbytes.json -pass pass:$ENCRYPTION_PASSPHRASE
            mv boto.cfg /tmp
            ls keys
            echo $PWD
            gcloud version
            gsutil version
            mkdir story
            gsutil -m cp -r gs://story.puneetghodasara.com/ story/
      - docker-publish/check
      - docker-publish/build
          tag: latest
      - docker-publish/deploy
