version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
  gcp-cli: circleci/gcp-cli@1.3.0
  aws-ecr: circleci/aws-ecr@3.1.0
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Decrypting Secrets
          command: |
            openssl aes-256-ecb -d -in keys/key.pem.enc -out keys/key.pem -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/cert.pem.enc -out keys/cert.pem -pass pass:$ENCRYPTION_PASSPHRASE
            openssl aes-256-ecb -d -in keys/config.ini.enc -out keys/config.ini -pass pass:$ENCRYPTION_PASSPHRASE
#            openssl aes-256-ecb -d -in keys/virtualbytes.json.enc -out keys/virtualbytes.json -pass pass:$ENCRYPTION_PASSPHRASE
      - run:
          name: Downloading stories
          command: |
            mkdir story
            gsutil -m cp -r gs://story.puneetghodasara.com/* story/
      - run:
          name: Cleaning up before build
          command: |
            rm keys/*.enc
#            rm keys/virtualbytes.json
      - run:
          name: Add revision
          command: |
            echo $CIRCLE_BUILD_NUM > revision.info
      - docker-publish/check
      - docker-publish/build:
          tag: latest
      - docker-publish/deploy
      - run:
          name: Tagging for all clouds
          command: |
            docker tag $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME $AWS_ACCOUNT_NUMBER.dkr-ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME
            docker images
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $CIRCLE_PROJECT_REPONAME

