version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
  gcp-cli: circleci/gcp-cli@1.3.0
  aws-ecr: circleci/aws-ecr@3.1.0
  aws-cli: circleci/aws-cli@0.1.13
  gcp-gcr: circleci/gcp-gcr@0.0.4
  azure-cli: circleci/azure-cli@1.0.3
commands:
  docker-login:
    steps:
      - run:
          name: Login to docker.io
          command: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
  docker-build:
    steps:
      - run:
          name: Building Docker Image
          command: docker build -t ${DOCKER_LOGIN}/${CONTAINER_NAME}:${CONTAINER_TAG} .
  docker-push:
    steps:
      - run:
          name: Pushing Image to docker.io
          command: docker push ${DOCKER_LOGIN}/${CONTAINER_NAME}:${CONTAINER_TAG}
  decrypt-secrets:
    steps:
      - run:
          name: Decrypting *.enc files
          command: for filename in keys/*; do openssl enc -aes-256-ecb  -in $filename -out $filename.enc -pass pass:$ENCRYPTION_PASSPHRASE; done
      - run:
          name: Deleting *.enc files
          command: rm keys/*.enc
  download-stories:
    steps:
      - run:
          name: Download Stories
          command: |
            mkdir story
            gsutil -m cp -r gs://story.puneetghodasara.com/* story/
  add-version-file:
    steps:
      - run:
          name: Adding revision.info
          command: echo $CIRCLE_BUILD_NUM > public/revision.info
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize
      - decrypt-secrets
      - download-stories
      - add-version-file
      - docker-login
      - docker-build
      - docker-push
#      - run:
#          name: Decrypting Secrets
#          command: |
#            openssl aes-256-ecb -d -in keys/key.pem.enc -out keys/key.pem -pass pass:$ENCRYPTION_PASSPHRASE
#            openssl aes-256-ecb -d -in keys/cert.pem.enc -out keys/cert.pem -pass pass:$ENCRYPTION_PASSPHRASE
#            openssl aes-256-ecb -d -in keys/config.ini.enc -out keys/config.ini -pass pass:$ENCRYPTION_PASSPHRASE
##            openssl aes-256-ecb -d -in keys/virtualbytes.json.enc -out keys/virtualbytes.json -pass pass:$ENCRYPTION_PASSPHRASE
#      - run:
#          name: Downloading Stories from Google Object Storage
#          command: |
#            mkdir story
#            gsutil -m cp -r gs://story.puneetghodasara.com/* story/
#      - run:
#          name: Cleaning up before build
#          command: |
#            rm keys/*.enc
##            rm keys/virtualbytes.json
#      - run:
#          name: Add revision file
#          command: |
#            echo $CIRCLE_BUILD_NUM > public/revision.info
#      - docker-publish/check
#      - docker-publish/build:
#
#          tag: $CUSTOM_TAG
#      - docker-publish/deploy:
#          image: $DOCKER_LOGIN/$CONTAINER_NAME:$CUSTOM_TAG
  aws-push:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - run:
          name: Python Preparation
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
      - aws-cli/install
      - aws-cli/configure
      - docker-publish/check
      - run:
          name: Tagging for AWS cloud
          command: |
            docker pull $DOCKER_LOGIN/$CONTAINER_NAME:$CUSTOM_TAG
            docker tag $DOCKER_LOGIN/$CONTAINER_NAME:$CUSTOM_TAG $AWS_ECR_ACCOUNT_URL/$CONTAINER_NAME:$CUSTOM_TAG
            docker images
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $CONTAINER_NAME
          tag: $CUSTOM_TAG
  gcp-push:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize
      - docker-publish/check
      - run:
          name: Pull Image
          command: |
            docker pull $DOCKER_LOGIN/$CONTAINER_NAME:$CUSTOM_TAG
            docker tag $DOCKER_LOGIN/$CONTAINER_NAME:$CUSTOM_TAG gcr.io/$GOOGLE_PROJECT_ID/$CONTAINER_NAME:$CUSTOM_TAG
            docker images
      - run:
          name: Testing GCloud auth
          command: |
            gcloud auth configure-docker --quiet --project $GOOGLE_PROJECT_ID
      - gcp-gcr/push-image:
          image: $CONTAINER_NAME
          tag: $CUSTOM_TAG
  azure-delivery:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Azure Restart
          command: |
            az configure --defaults group=$AZURE_WEBAPP_RESOURCE_NAME
            az webapp restart -n $AZURE_WEBAPP_NAME
  gcp-delivery:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - gcp-cli/install
      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_CIRCLECI_SERVICE_KEY
      - run:
          name: Delivering Container to Google Cloud Platform
          command: |
            gcloud compute instances update-container $GCP_WEBAPP_NAME --zone $GOOGLE_COMPUTE_ZONE
  aws-delivery:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - run:
          name: Python Preparation
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Delivering Container to AWS
          command: |
            TASK_ID=`aws ecs list-tasks --desired-status RUNNING --launch-type EC2 | jq -r '.taskArns[0]'`
            echo $TASK_ID would stop
            aws ecs stop-task --task $TASK_ID
            aws ecs run-task --task-definition $AWS_TASK_DEF_NAME --launch-type EC2

workflows:
  build-flow:
    jobs:
      - build
#      - aws-push:
#          requires:
#            - build
#      - gcp-push:
#          requires:
#            - build
#      - azure-delivery:
#          requires:
#            - build
#      - gcp-delivery:
#          requires:
#            - gcp-push
#      - aws-delivery:
#          requires:
#            - aws-push

