version: 2.1
orbs:
  docker-publish: circleci/docker-publish@1.0.0
workflows:
  docker_with_lifecycle:
    jobs:
      - my_custom_build
jobs:
  - my_custom_build:
      executor: docker-publish/publish